import fs from 'node:fs';
import path from 'node:path';
import { homedir } from 'node:os';
import { execFileSync } from 'node:child_process';
const lock = JSON.parse(fs.readFileSync('package-lock.json', 'utf8'));
const npm = [];
for (const [key, entry] of Object.entries(lock.packages)) {
  if (!key || !key.includes('node_modules/')) continue;
  const name = key.slice(key.lastIndexOf('node_modules/') + 13);
  const file = path.join(key, 'package.json');
  const pkg = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : {};
  npm.push({
    name,
    version: entry.version,
    license: pkg.license || entry.license || 'UNKNOWN',
    scope: entry.dev ? 'development' : 'runtime',
  });
}
const cargoHome = process.env.CARGO_HOME || path.join(homedir(), '.cargo');
const cargoBinary = path.join(cargoHome, 'bin', process.platform === 'win32' ? 'cargo.exe' : 'cargo');
const cargo = process.env.CARGO || (fs.existsSync(cargoBinary) ? cargoBinary : 'cargo');
const metadata = JSON.parse(
  execFileSync(
    cargo,
    ['metadata', '--locked', '--manifest-path', 'src-tauri/Cargo.toml', '--format-version', '1'],
    { maxBuffer: 20 * 1024 * 1024 },
  ),
);
const rust = metadata.packages
  .filter((p) => p.name !== 'markraft')
  .map((p) => ({ name: p.name, version: p.version, license: p.license || 'UNKNOWN' }));
function table(packages) {
  return (
    '| Package | Version | License |\n| --- | --- | --- |\n' +
    packages
      .sort((a, b) => a.name.localeCompare(b.name))
      .map((p) => `| ${p.name} | ${p.version} | ${p.license} |`)
      .join('\n')
  );
}
fs.writeFileSync(
  'DEPENDENCIES.md',
  `# Dependency inventory\n\nGenerated by \`npm run licenses\` from installed npm metadata and Cargo.lock. Rust includes build tools and all platform targets. License expressions retain their upstream alternatives; MIT/Apache alternatives are preferred where offered. Markraft itself is MIT-licensed; see [LICENSE](LICENSE). Third-party components retain their own licenses.\n\n## Specification conflict: transitive MPL dependencies\n\nThe required Tauri 2 stack pulls in MPL-2.0 dependencies (including option-ext, cssparser, cssparser-macros, dtoa-short, selectors). Therefore this project **does not currently satisfy the specification's absolute no-copyleft-dependency constraint**. Direct application dependencies use permissive licenses. This inventory is not a legal clearance or permission to ignore upstream terms. See [DEPENDENCY_REVIEW.md](DEPENDENCY_REVIEW.md) for the policy review, scope limitations, and MPL source links. Retain required third-party notices when distributing builds.\n\n## npm runtime\n\n${table(npm.filter((p) => p.scope === 'runtime'))}\n\n## npm development\n\n${table(npm.filter((p) => p.scope === 'development'))}\n\n## Cargo (all targets, including build dependencies)\n\n${table(rust)}\n`,
);
const notices = ['Markraft — Third-party notices\n\nMarkraft itself is licensed under the MIT License; see LICENSE.\nThe components below retain their own licenses and copyright notices.\nThis collection includes development and platform-specific dependencies.\nSee DEPENDENCIES.md for the inventory and DEPENDENCY_REVIEW.md for MPL source links.\nUpstream license texts below are reproduced without translation.\n'];
function collect(dir, label) {
  for (const file of fs.readdirSync(dir))
    if (
      /^(LICENSE|COPYING|NOTICE)([.-]|$)/i.test(file) &&
      fs.statSync(path.join(dir, file)).isFile()
    )
      notices.push(
        `\n${'='.repeat(80)}\n${label} — ${file}\n${'='.repeat(80)}\n${fs.readFileSync(path.join(dir, file), 'utf8')}\n`,
      );
}
for (const pkg of metadata.packages)
  if (pkg.name !== 'markraft')
    collect(path.dirname(pkg.manifest_path), `${pkg.name} ${pkg.version} (Cargo)`);
for (const [key] of Object.entries(lock.packages))
  if (key && fs.existsSync(path.join(key, 'package.json'))) {
    const pkg = JSON.parse(fs.readFileSync(path.join(key, 'package.json'), 'utf8'));
    collect(key, `${pkg.name} ${pkg.version} (npm)`);
  }
fs.writeFileSync('THIRD_PARTY_NOTICES.txt', notices.join(''));
console.log(
  `Recorded ${npm.length} npm and ${rust.length} Rust dependencies, plus upstream notices.`,
);
